name: Build zydeco/fusemfs Xcode Project

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Install dependencies
        run: |
          brew update
          brew install cmake

      - name: Build Xcode project
        run: |
          xcodebuild -project fusemfs.xcodeproj -scheme fusemfs -configuration Release build

      - name: Run Tests
        run: |
          xcodebuild test -project fusemfs.xcodeproj -scheme fusemfs -configuration Debug -destination 'platform=macOS'
