name: test14

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-and-build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Install dependencies
        run: |
          brew update
          brew install cmake

      - name: Update Xcode project settings
        run: |
          # Update the SDKROOT to use the latest macOS SDK
          /usr/libexec/PlistBuddy -c "Set :SDKROOT macosx" FuseMFS.xcodeproj/project.pbxproj
          
          # Update the supported architectures to include only arm64 and x86_64
          /usr/libexec/PlistBuddy -c "Set :ARCHS '$(ARCHS_STANDARD_64_BIT)'" FuseMFS.xcodeproj/project.pbxproj
          /usr/libexec/PlistBuddy -c "Set :ONLY_ACTIVE_ARCH YES" FuseMFS.xcodeproj/project.pbxproj

      - name: Build Xcode project for arm64
        run: |
          xcodebuild -project FuseMFS.xcodeproj -scheme fusemfs -configuration Release -arch arm64 build

      - name: Build Xcode project for x86_64
        run: |
          xcodebuild -project FuseMFS.xcodeproj -scheme fusemfs -configuration Release -arch x86_64 build

      - name: Run Tests for arm64
        run: |
          xcodebuild test -project FuseMFS.xcodeproj -scheme fusemfs -configuration Debug -destination 'platform=macOS,arch=arm64'

      - name: Run Tests for x86_64
        run: |
          xcodebuild test -project FuseMFS.xcodeproj -scheme fusemfs -configuration Debug -destination 'platform=macOS,arch=x86_64'
