name: test7

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-and-build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: brew install cmake

      - name: Update Xcode project settings
        run: |
          # Update the SDKROOT to the latest macOS SDK
          plutil -replace objects.1DEB928A08733DD80010E9CD.buildSettings.SDKROOT -string macosx13.0 FuseMFS.xcodeproj/project.pbxproj
          plutil -replace objects.1DEB928B08733DD80010E9CD.buildSettings.SDKROOT -string macosx13.0 FuseMFS.xcodeproj/project.pbxproj
          
          # Update the architectures to use standard architectures
          plutil -replace objects.1DEB928A08733DD80010E9CD.buildSettings.ARCHS -string "$(ARCHS_STANDARD)" FuseMFS.xcodeproj/project.pbxproj
          plutil -replace objects.1DEB928B08733DD80010E9CD.buildSettings.ARCHS -string "$(ARCHS_STANDARD)" FuseMFS.xcodeproj/project.pbxproj
          
          # Remove unsupported architectures
          plutil -replace objects.1DEB928A08733DD80010E9CD.buildSettings.VALID_ARCHS -string "$(ARCHS_STANDARD)" FuseMFS.xcodeproj/project.pbxproj
          plutil -replace objects.1DEB928B08733DD80010E9CD.buildSettings.VALID_ARCHS -string "$(ARCHS_STANDARD)" FuseMFS.xcodeproj/project.pbxproj

      - name: Build with Xcode
        run: xcodebuild -project FuseMFS.xcodeproj -scheme fusemfs -sdk macosx -configuration Release build
