name: Update and Build zydeco/fusemfs Xcode Project

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-and-build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Update Xcode project to current macOS SDK
        run: |
          # Update project settings to current macOS standards
          xcodebuild -project fusemfs.xcodeproj -target fusemfs -sdk macosx -configuration Release build

      - name: Build Xcode project for arm64
        run: |
          xcodebuild -project fusemfs.xcodeproj -scheme fusemfs -configuration Release -arch arm64 build

      - name: Run Tests
        run: |
          xcodebuild test -project fusemfs.xcodeproj -scheme fusemfs -configuration Debug -destination 'platform=macOS,arch=arm64'
